### ISSUE TITLE
Export fails on git v2.17.1 with ruby-git 1.3.0

### ISSUE THREAD

**Issue by dandunckelman** [theforeman/foreman_templates#107]
# Summary

I'm trying to export templates to my own git repo (hosted on an internal Gitlab).

Imports work as expected.

## Environment:

- **OS:** Ubuntu 18.04
- **Foreman version:** 1.20.1
- **Foreman templates plugin version:** 6.0.3
- **Git version:** 2.17.1

## What I've done by following [this guide](https://theforeman.org/plugins/foreman_templates/6.0/index.html#3.1ExampleofconfigurationGitHubrepository)

- Update the repo setting on foreman w/ this:

      hammer settings set --name template_sync_branch --value master
      hammer settings set --name --value ssh://git@mygitlab/mygroup/foreman-provisioning-templates.git
- Add our gitlab's host key:

      ssh-keyscan -H mygitlab >> /usr/share/foreman/.ssh/known_hosts
      chown foreman:foreman /usr/share/foreman/.ssh/known_hosts
- I created a SSH key on foreman with this:

      sudo -u foreman ssh-keygen
- Using the public key, I created a deploy key in the Gitlab project's "Deploy keys" (I verified I could clone the repo)
- I installed the hammer cli templates plugin:

      gem install hammer_cli_foreman_templates
- I then ran this

      hammer export-template --verbose true
- Got this error:

      "git '--git-dir=/tmp/d20190110-1928-2om4sm/.git' '--work-tree=/tmp/d20190110-1928-2om4sm' ls-files '--stage' ''  2>&1:fatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths"

I see that the [ruby-git](https://github.com/ruby-git/ruby-git/) version bundled w/ my foreman is `1.3.0`:

```
cat /usr/share/foreman/Gemfile.lock |grep git
      git                                                       
    git (1.3.0)                                                 
```

## Similar issues:

- https://github.com/theforeman/foreman_templates/issues/42
- https://github.com/ruby-git/ruby-git/issues/345
- https://github.com/ruby-git/ruby-git/pull/350
  - I believe this fixes it for git v2.16.0 in ruby-git v1.4.0, which might also solve it for 2.17.1

**Comment by ares** [comment]
How did you install foreman? We seems to ship gem git in version of 1.25 in nightlies. In package based installation, Gemfile.lock is not honored. If you installed from source, just update the gem using `bundle update git` and let us know.

**Comment by dandunckelman** [comment]
I used Foreman installer

**Comment by ares** [comment]
oops sorry, just realized we have 1.3.0 on debian based distros, I'll build scratch packages, it would be great if you'd test

**Comment by ares** [comment]
could you pls try installing http://stagingdeb.theforeman.org/pool/plugins/ares/r/ruby-foreman-templates/ruby-foreman-templates_9999-plugin+scratchbuild+20190111084941_all.deb and then restarting Foreman and see if it helps?

**Comment by dandunckelman** [comment]
@ares should I do this?

```
wget http://stagingdeb.theforeman.org/pool/plugins/ares/r/ruby-foreman-templates/ruby-foreman-templates_9999-plugin+scratchbuild+20190111084941_all.deb
dpkg -i ruby-foreman-templates_9999-plugin+scratchbuild+20190111084941_all.deb
rm ruby-foreman-templates_9999-plugin+scratchbuild+20190111084941_all.deb
systemctl restart apache2
```

And how would I revert back to v6.0.3 stable? This?

```
apt-get purge -y ruby-foreman-templates
apt install -y ruby-foreman-templates # I think this would install from the apt repo `deb.theforeman.org plugins/1.20`
```

Or would it be better to use foreman-installer like this?

```
foreman-installer --enable-foreman-plugin-templates
```

**Comment by ares** [comment]
Steps you suggested seems correct, instead of apt-get purge, I'd just uninstall before reinstalling. Or take lvm/vm snapshot and restore after testing if possible. Running foreman installer should not be required in this case.

**Comment by dandunckelman** [comment]
@ares I'm currently reviewing the commit, but it looks like it worked as expected.  Thanks.

Do you want to keep this issue open as you finish https://github.com/theforeman/foreman-packaging/pull/3348 ?

**Comment by ares** [comment]
I think we can close now, packaging PRs will get in soon hopefully. Thanks for testing, let us know if you find regression with new version.

**Comment by dandunckelman** [comment]
@ares I'm revisiting this as I look to upgrade Foreman and all related packages.

But AFAIK, v6.0.3 is still the only release that comes out of the box.

I also found that https://theforeman.org/plugins/foreman_templates/ doesn't have a docs page for 7.x

Who do we need to bump to get 7.x incorporated in the foreman apt (and other) repo?
