### ISSUE TITLE
Updating locked templates fails

### ISSUE THREAD

**Issue by Pimmetje** [theforeman/foreman_templates#108]
I loaded the templates from theforeman server. After this i imported them with Lock templates: yes. 
Making all my templates locked. 

Now i want to update a template using git. I try to pull the repo but foreman complains about the template being locked. 
I want the template to be locked in foreman. But i still like to be able to make changes using git.

**Comment by xprazak2** [comment]
Hi,
have you tried the `force: true` option? It should do exactly what you need.

**Comment by Pimmetje** [comment]
I guess i overlooked that one. Thanks!
