### ISSUE TITLE
ptables support (foreman 1.9)

### ISSUE THREAD

**Issue by alexdga** [theforeman/foreman_templates#18]
I use a custom git repository for my provisioning templates in foreman.

Can you add support for ptables which are now templates since foreman 1.9 plz ?

**Comment by ares** [comment]
when I originally looked at this, it wasn't trivial task since there's a lot of hardcoded stuff in rake script, any help would be appreciated

**Comment by Jenpatrick** [comment]
Also would really love this feature.  Not sure how much I can contribute to help, but it is needed/wanted.

**Comment by GregSutcliffe** [comment]
The UI branch of the plugin needs updating, but part of that branch moves the code out of one massive rake task and into proper service modules. That may remove Marek's issue with extending it. No promises but I'll try to do that in the next few weeks ;)

**Comment by ares** [comment]
@GregSutcliffe please let me know when the branch gets in, I'd be happy to revisit it and hopefully use it for job templates as well

**Comment by GregSutcliffe** [comment]
I believe all forms of PTable (including ptable snippets) are now importable with Templates 3.0.0. As such, I'm going to close this, but do open a new issue if there's still problems.
