### ISSUE TITLE
support ssh agent for git clone

### ISSUE THREAD

**Issue by stevie-** [theforeman/foreman_templates#31]
We would like to use foremna_templates to pull from our private git repo. Thus we always need to support credentials. 
Putting credentials in a git HTTPS url using basic auth is not very flexible nor secure.

```
repo='https://username:password@git.domain.net/path/to.git'
```

Thus we could use ssh git url which is very flexible and makes use of ssh keypair.

```
repo='ssh://git@git.domian.net:22/path/to.git'
```

But apperently rake is not using SSH-Agent from ssh login.

```
foreman-rake templates:sync associate='always' repo="ssh://git@git.domain.net:22/path/to.git" prefix="MY"
rake aborted!
Git::GitExecuteError: git  clone '--' 'ssh://git@git.domain.net:22/path/to.git' '/tmp/d20161007-26134-zix809'  2>&1:Cloning into '/tmp/d20161007-26134-zix809'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
/usr/share/foreman/vendor/ruby/2.0.0/gems/git-1.2.9.1/lib/git/lib.rb:917:in `command'
/usr/share/foreman/vendor/ruby/2.0.0/gems/git-1.2.9.1/lib/git/lib.rb:76:in `clone'
/usr/share/foreman/vendor/ruby/2.0.0/gems/git-1.2.9.1/lib/git/base.rb:29:in `clone'
/usr/share/foreman/vendor/ruby/2.0.0/gems/git-1.2.9.1/lib/git.rb:97:in `clone'
/usr/share/foreman/vendor/ruby/2.0.0/gems/foreman_templates-3.1.0/app/services/foreman_templates/template_importer.rb:34:in `import!'
/usr/share/foreman/vendor/ruby/2.0.0/gems/foreman_templates-3.1.0/lib/tasks/foreman_templates_tasks.rake:22:in `block (2 levels) in <top (required)>'
/usr/bin/rake2.0:37:in `<main>'
Tasks: TOP => templates:sync
(See full trace by running task with --trace)
```

if we run command on shell it works

```
git  clone '--' 'ssh://git@git.domain.net:22/path/to.git' '/tmp/d20161007-20901-qbjk9t'
```

Could we make rake aware of SSH-Agent ?

**Comment by GregSutcliffe** [comment]
I'll have to look into it - the plugin just calls the 'git' rubygem directly, nothing fancy, so it'll depend if that supports it, and if so, what needs to happen on this side to hook into it.

**Comment by sean797** [comment]
@stevie- i think the problem is from the shell you're running it as one user, maybe root? `foreman-rake templates:sync associate='always' repo="ssh://git@git.domain.net:22/path/to.git" prefix="MY"` runs as the foreman user, try running it from the shell as the foreman user, i think you will get the same error.

**Comment by stevie-** [comment]
Yeah, this makes sense. It would work if we use `sudo -u foreman` to call foreman-rake instead os `su`, which will inherits ssh-agent environment variables.
Another thing I tested is using a public github repo with ssh, which also failed. Only http(s) works. Can you reproduce this?

**Comment by sean797** [comment]
Yes, that works. You'll need to add your SSH public key into your github account or as a "deploy key" on the repo and it should work. What error did you get?

**Comment by stevie-** [comment]
Ok, so ssh works in general - probably jsut a github setup issue I had.

To make this work with ssh-agent, we need to `sudo` to root to be able to access ssh-agent socket or run git as logged in user.

**Comment by sean797** [comment]
@stevie- I'm not quite sure what you mean, if you setup the ssh key for the foreman user it should work?

**Comment by stevie-** [comment]
I'm talking about SSH-agent support.
This is done via Environment variables and only the user who created the agent socket or root can access it.
```
$ echo $SSH_AUTH_SOCK
/tmp/ssh-LVyMx7Pipv/agent.6393
```

**Comment by sean797** [comment]
humm... I thought i replied to this, anyway. Why would you need this? Are there any benefits as opposed to using ssh keys? 

Either way I can't see this being implemented here until git rubygem supports it as @GregSutcliffe said earlier.
