### ISSUE TITLE
Sync with prefix should replace referenced templates with prefix

### ISSUE THREAD

**Issue by Trefex** [theforeman/foreman_templates#49]
Hi,

Currently when you sync templates with a prefix, the snippets referenced are not updated.

Ideally, it would update the referenced templates too and replace them with a prefix.

**Comment by GregSutcliffe** [comment]
This should probably be an option, since I can see times when you *wouldn't* want to update references. Otherwise +1, particularly in the use case of people syncing upstream community-templates to a prefix.

**Comment by Trefex** [comment]
@GregSutcliffe that's how we use it currently. We have FreeIPA / Puppet setup, so the community templates suit us just fine currently.

**Comment by Zugschlus** [comment]
What would be the use case for _not_ importing the snippet name with a prefix? Keeping the original snippet name is inviting trouble in updates since a foreman update will overwrite locally changed snippets.
That being said, yes, please implement that.

**Comment by xprazak2** [comment]
I created an issue in [Redmine](https://projects.theforeman.org/issues/24297), feel free to add any comments there.
