### ISSUE TITLE
Taxonomy is not set

### ISSUE THREAD

**Issue by lzap** [theforeman/foreman_templates#60]
A setting to set taxonomy would make lot of sense in Satellite context. All imported templates are missing taxonomy completely.

**Comment by sean797** [comment]
This should already work https://github.com/theforeman/foreman_templates/commit/1b55133606ada87d028b6c6b6dc2c922b8fd4b0c

Metadata should be like:

```
<%#
kind: provision
name: Kickstart RHEL default
oses:
- RedHat
locations:
- London
- Paris
organizations:
- foo
- bar
%>

**Comment by lzap** [comment]
Cool!
