### ISSUE TITLE
Unable to import from a local github

### ISSUE THREAD

**Issue by xjparkerx** [theforeman/foreman_templates#69]
We have an internal github instance that has a self signed cert.  So I've been using git config --global http.sslverify false in order to push/pull.  How would I enable that for the foreman_templates plugin?

**Comment by sean797** [comment]
@xjparkerx `http.sslCAPath` would have been better ;) anyway what you are going is the correct way.

See https://github.com/theforeman/theforeman.org/pull/967

**Comment by xjparkerx** [comment]
Thanks for your help

**Comment by ares** [comment]
The documentation PR has been merged, I think we can close this as resolved. Thanks @sean797 for quick action!
