### ISSUE TITLE
purge does not remove partition tables

### ISSUE THREAD

**Issue by Zugschlus** [theforeman/foreman_templates#85]
Hi,
in a test installation, I experimented with template:sync and imported the community templates first with a foo, then with a foo- prefix. Both sync were cleaned up with a corresponding template:purge. However, the foo and foo- prefixed partition tables remained in the database.
Greetings
Marc

**Comment by ares** [comment]
Hello, thanks for the report.

Purge task was deprecated and not API for triggering it is planned, it's probably best to search for templates matching foo- prefix and then for each perform the deletion. The default prefix is now empty too.

While purge task could have been very convenient way of deletion if user imported something that he/she did not expect, it was too hacky and perhaps also dangerous way to delete data from DB.
