### ISSUE TITLE
TemplateSync importing only to DB and not UI in Foreman 1.17

### ISSUE THREAD

**Issue by trinaryouroboros** [theforeman/foreman_templates#98]
Having a problem with 1.17, think this worked before, not sure why a month later this isn't working.

We have a custom git repo for templates, that we set up in the TemplateSync settings.

We perform:
`/sbin/foreman-rake templates:import`

It shows our prefixed templates get imported successfully. If we select the given name from the mysql db it returns a row successfully. In the UI, however, this provisioning template does not appear. None of them do. We checked things like possibly a bad name / etc. and have run out of ideas of what could be wrong.

When performing:
`/sbin/foreman-rake templates:purge`

It does indeed show the records being removed properly from the DB.

Name        : tfm-rubygem-foreman_templates
Arch        : noarch
Version     : 5.0.1
Release     : 2.fm1_17.el7

**Comment by trinaryouroboros** [comment]
**Extra note:** We believe when TemplateSync worked, we went from using a system deployed with an older 1.15 puppet module, to manually modifying the yum repos on that system to upgrade manually. This time we are using the latest puppet module, specifying 1.17 in the puppet config. I believe that's the only thing that's different.

**Comment by ares** [comment]
Do you use organizations/locations? Do you see them under admin user? Note 
that in 1.15, there was a big change that regular users don't see objects 
not assigned to any org/loc. What you describe sounds like this case. Also 
note that using foreman-rake is deprecated, there's now rest API for 
performing import and export.

Hope that helps

--
Marek

**Comment by trinaryouroboros** [comment]
That was it! :)

Silly, I didn't realize locations weren't automatically added to the admin user.

It makes sense why this worked before using manual upgrade, as the locations were already assigned to the admin user.  I just had to set the locations for the admin user now and foreman-rake import worked fine.

Just curious what the new way to do the import is? Obviously this git readme is out of date.

**Comment by ares** [comment]
see https://www.theforeman.org/plugins/foreman_templates/5.0/index.html#5.API I'll update the readme so it points to the manual, thanks
